apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-heat-submission-service
  labels:
    app: swtdisp-grp10-heat-submission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swtdisp-grp10-heat-submission-pod

  template:
    metadata:
      name: swtdisp-grp10-heat-submission-pod
      labels:
        app: swtdisp-grp10-heat-submission-pod
    spec:
      containers:
        - name: swtdisp-grp10-heat-submission-service-container
          image: mark2830/heat_submission_service
          ports:
            - containerPort: 80        