apiVersion: v1
kind: Service
metadata:
  name: swtdisp-grp10-rabbitmq-service
  namespace: swtdisp-ap1-gr10
spec:
  clusterIP: None
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: cluster-rpc
    port: 25672
    protocol: TCP
    targetPort: 25672
  selector:
    app: swtdisp-grp10-rabbitmq
  type: ClusterIP
  sessionAffinity: None