---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swtdisp-grp10-rabbitmq
  namespace: swtdisp-ap1-gr10
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: swtdisp-grp10-rabbitmq
  namespace: swtdisp-ap1-gr10
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: swtdisp-grp10-rabbitmq
  namespace: swtdisp-ap1-gr10
subjects:
- kind: ServiceAccount
  name: swtdisp-grp10-rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: swtdisp-grp10-rabbitmq
