apiVersion: v1
kind: Service
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-public-charging-service-service
  labels:
    app: swtdisp-grp10-public-charging-service-service
    
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: public-charging-service-pod