apiVersion: v1
kind: Service
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-iot_heat_metering_unit-service
  labels:
    app: swtdisp-grp10-iot_heat_metering_unit-service
      
spec:
   type: NodePort
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80
   selector:
     app: tecaisiotheatmeteringunit-pod