version: '3.4'

services:
  tecais.heatsaga:
    container_name: heatsaga
    image: ${DOCKER_REGISTRY-}heatsaga4
    networks:
      - disp
    build:
      context: .
      dockerfile: TECAIS.HeatSaga/Dockerfile
    ports:
      - 9000:80
      - 44366:80
    restart: always
networks:
  disp:
    external: 
      name: disp