apiVersion: v1
kind: Service
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-accounting-command-handler-service
  labels:
    app: swtdisp-grp10-accounting-command-handler-service
    
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: accounting-command-handler-pod