apiVersion: v1
kind: Service
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-heat-status-submission-service
  labels:
    app: swtdisp-grp10-heat-status-submission-service
    
spec:
<<<<<<< HEAD
  type: NodePort
=======
  type: ClusterIP
>>>>>>> f7f0c5813b4b58f8e2ba570c553cd4ece3ca1e15
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: heat-status-submission-service-pod