apiVersion: apps/v1
kind: StatefulSet 
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-rabbitmq
  labels:
    app: swtdisp-grp10-rabbitmq
spec:
  serviceName: swtdisp-grp10-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: tecaisrabbitmq-pod
  template:
    metadata:
      name: tecaisrabbitmq-pod
      labels:
        app: tecaisrabbitmq-pod
    spec:
      containers:
        - name: swtdisp-grp10-rabbitmq-container
          image: rabbitmq:3-management
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP