apiVersion: v1
kind: Service
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-heat-pricing-service-service
  labels:
    app: swtdisp-grp10-heat-pricing-service-service
      
spec:
   type: ClusterIP
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80
   selector:
     app: heat-pricing-service-pod